/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-tint": "#ed4e2c",
        "surface-bright": "#f7f9fb",
        "on-background": "#191c1e",
        "primary-fixed-dim": "#ffb4a3",
        "on-surface-variant": "#53433f",
        "on-primary-fixed-variant": "#7c0000",
        "tertiary-fixed": "#ffdad7",
        "on-primary": "#ffffff",
        "tertiary-container": "#fc7c78",
        "surface-container-low": "#f2f4f6",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed": "#002113",
        "on-primary-container": "#410002",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceef0",
        "secondary-fixed": "#baeed1",
        "outline": "#857370",
        "surface-variant": "#e0e3e5",
        "on-error": "#ffffff",
        "primary-fixed": "#ffdad2",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "background": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-container": "#711419",
        "on-primary-fixed": "#3a0a01",
        "tertiary": "#a43a3a",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-fixed-variant": "#842225",
        "on-tertiary-fixed": "#410005",
        "on-secondary-fixed-variant": "#5d3f3b",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2d3133",
        "secondary": "#775652",
        "secondary-fixed-dim": "#9ed2b5",
        "secondary-container": "#b7ebce",
        "primary-container": "#ffdad2",
        "primary": "#ed4e2c",
        "surface-dim": "#d8dadc",
        "tertiary-fixed-dim": "#ffb3af",
        "outline-variant": "#bbcabf",
        "inverse-primary": "#ffb4a3",
        "surface": "#f7f9fb",
        "on-secondary-container": "#3c6c54",
        "on-error-container": "#93000a",
        "on-surface": "#191c1e",
        "on-secondary": "#ffffff"
      },
      "borderRadius": {
        "none": "0",
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "full": "9999px"
      },
      "boxShadow": {
        "premium": "0 10px 25px -5px rgba(0, 0, 0, 0.04), 0 8px 10px -6px rgba(0, 0, 0, 0.04)",
        "premium-hover": "0 20px 25px -5px rgba(0, 0, 0, 0.08), 0 8px 10px -6px rgba(0, 0, 0, 0.08)",
        "glass": "inset 0 0 0 1px rgba(255, 255, 255, 0.1)",
      },
      "fontFamily": {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
